from django.db import models


# Create your models here.



class Result(models.Model):
    Answer_choice = ((1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다'))
    age_choice = ((1, '10대'), (2, '20대'), (3, '30대'), (4, '40대'), (5, '50대'), (6, '60대'))
    edu_choice = ((1, '고졸미만'), (2, '고졸'), (3, '대졸'), (4, '석사'))
    engant_choice = ((1, '네'), (2, '아니오'))
    family_choice = ((1, '1명'), (2, '2명'), (3, '3명 이상'))
    gender_choice = ((1, '남자'), (2, '여자'))
    hand_choice = ((1, '오른손'), (2, '왼손'), (3, '양손'))
    married_choice = ((1, '미혼'), (2, '최근 결혼'), (3, '결혼 10년차 이상'), (4, '돌싱'))
    race_choice = ((1, '아시아인'), (2, '아랍'), (3, '흑인'), (4, '백인'), (5, '그 외'))
    religion_choice = ((2, '무교'), (3, '불교'), (4, '크리스찬'), (5, '무슬림'), (6, '그 외'))
    tp_choice = ((0, '매우 강한 부정'), (1, '강한 부정'), (2, '약한 부정'), (3, '매우 약한 부정'), (4, '매우 약한 긍정'), (5, '약한 긍정'), (6, '강한 긍정'),
    (7, '매우 강한 긍정'))
    urban_choice = ((1, '시골'), (2, '교외 지역'), (3, '도시'))

    Name=models.CharField(max_length=200,blank=True)
    Question1 = models.IntegerField(null=True,blank=True,choices=Answer_choice)
    Question2 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question3 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question4 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question5 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question6 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question7 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question8 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question9 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question10 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question11 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question12 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question13 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question14 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question15 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question16 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question17 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question18 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question19 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question20 = models.IntegerField(null=True, blank=True, choices=Answer_choice)
    Question21 = models.IntegerField(null=True, blank=True, choices=age_choice)
    Question22 = models.IntegerField(null=True, blank=True, choices=edu_choice)
    Question23 = models.IntegerField(null=True, blank=True, choices=engant_choice)
    Question24 = models.IntegerField(null=True, blank=True, choices=family_choice)
    Question25 = models.IntegerField(null=True, blank=True, choices=gender_choice)
    Question26 = models.IntegerField(null=True, blank=True, choices=hand_choice)
    Question27 = models.IntegerField(null=True, blank=True, choices=married_choice)
    Question28 = models.IntegerField(null=True, blank=True, choices=race_choice)
    Question29 = models.IntegerField(null=True, blank=True, choices=religion_choice)
    Question30 = models.IntegerField(null=True, blank=True, choices=tp_choice)
    Question31 = models.IntegerField(null=True, blank=True, choices=tp_choice)
    Question32 = models.IntegerField(null=True, blank=True, choices=tp_choice)
    Question33 = models.IntegerField(null=True, blank=True, choices=tp_choice)
    Question34 = models.IntegerField(null=True, blank=True, choices=tp_choice)
    Question35 = models.IntegerField(null=True, blank=True, choices=tp_choice)
    Question36 = models.IntegerField(null=True, blank=True, choices=tp_choice)
    Question37 = models.IntegerField(null=True, blank=True, choices=tp_choice)
    Question38 = models.IntegerField(null=True, blank=True, choices=tp_choice)
    Question39 = models.IntegerField(null=True, blank=True, choices=tp_choice)
    Question40 = models.IntegerField(null=True, blank=True, choices=urban_choice)
    voted=models.CharField(max_length=200,blank=True,null=True)
