# Generated by Django 3.1.7 on 2021-03-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210313_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='Question',
        ),
        migrations.AddField(
            model_name='result',
            name='Question1',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question10',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question11',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question12',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question13',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question14',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question15',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question16',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question17',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question18',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question19',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question2',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question20',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question21',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question22',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question23',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question24',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question25',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question26',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question27',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question28',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question29',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question3',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question30',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question31',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question32',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question33',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question34',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question35',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question36',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question37',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question38',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question39',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question4',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question40',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question5',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question6',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question7',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question8',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Question9',
            field=models.IntegerField(blank=True, choices=[(1, '매우아니다'), (2, '아니다'), (3, '보통'), (4, '그렇다'), (5, '매우그렇다')], null=True),
        ),
    ]
