# Generated by Django 3.1.7 on 2021-03-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20210317_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Question21',
            field=models.IntegerField(blank=True, choices=[(1, '10대'), (2, '20대'), (3, '30대'), (4, '40대'), (5, '50대'), (6, '60대')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question22',
            field=models.IntegerField(blank=True, choices=[(1, '고졸미만'), (2, '고졸'), (3, '대졸'), (4, '석사')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question23',
            field=models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question24',
            field=models.IntegerField(blank=True, choices=[(1, '1명'), (2, '2명'), (3, '3명 이상')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question25',
            field=models.IntegerField(blank=True, choices=[(1, '남자'), (2, '여자')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question26',
            field=models.IntegerField(blank=True, choices=[(1, '오른손'), (2, '왼손'), (3, '양손')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question27',
            field=models.IntegerField(blank=True, choices=[(1, '미혼'), (2, '최근 결혼'), (3, '결혼 10년차 이상'), (4, '돌싱')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question28',
            field=models.IntegerField(blank=True, choices=[(1, '아시아인'), (2, '아랍'), (3, '흑인'), (4, '백인'), (5, '그 외')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question29',
            field=models.IntegerField(blank=True, choices=[(2, '무교'), (3, '불교'), (4, '크리스찬'), (5, '무슬림'), (6, '그 외')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question30',
            field=models.IntegerField(blank=True, choices=[(1, '예'), (2, '아니오')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question31',
            field=models.IntegerField(blank=True, choices=[(1, '예'), (2, '아니오')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question32',
            field=models.IntegerField(blank=True, choices=[(1, '예'), (2, '아니오')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question33',
            field=models.IntegerField(blank=True, choices=[(1, '예'), (2, '아니오')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question34',
            field=models.IntegerField(blank=True, choices=[(1, '예'), (2, '아니오')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question35',
            field=models.IntegerField(blank=True, choices=[(1, '예'), (2, '아니오')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question36',
            field=models.IntegerField(blank=True, choices=[(1, '예'), (2, '아니오')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question37',
            field=models.IntegerField(blank=True, choices=[(1, '예'), (2, '아니오')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question38',
            field=models.IntegerField(blank=True, choices=[(1, '예'), (2, '아니오')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question39',
            field=models.IntegerField(blank=True, choices=[(1, '예'), (2, '아니오')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question40',
            field=models.IntegerField(blank=True, choices=[(1, '시골'), (2, '교외 지역'), (3, '도시')], null=True),
        ),
    ]
