# Generated by Django 3.1.7 on 2021-03-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20210317_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='D_result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
