# Generated by Django 3.1.7 on 2021-03-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20210317_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Question30',
            field=models.IntegerField(blank=True, choices=[(0, '매우 강한 부정'), (1, '강한 부정'), (2, '약한 부정'), (3, '매우 약한 부정'), (4, '매우 약한 긍정'), (5, '약한 긍정'), (6, '강한 긍정'), (7, '매우 강한 긍정')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question31',
            field=models.IntegerField(blank=True, choices=[(0, '매우 강한 부정'), (1, '강한 부정'), (2, '약한 부정'), (3, '매우 약한 부정'), (4, '매우 약한 긍정'), (5, '약한 긍정'), (6, '강한 긍정'), (7, '매우 강한 긍정')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question32',
            field=models.IntegerField(blank=True, choices=[(0, '매우 강한 부정'), (1, '강한 부정'), (2, '약한 부정'), (3, '매우 약한 부정'), (4, '매우 약한 긍정'), (5, '약한 긍정'), (6, '강한 긍정'), (7, '매우 강한 긍정')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question33',
            field=models.IntegerField(blank=True, choices=[(0, '매우 강한 부정'), (1, '강한 부정'), (2, '약한 부정'), (3, '매우 약한 부정'), (4, '매우 약한 긍정'), (5, '약한 긍정'), (6, '강한 긍정'), (7, '매우 강한 긍정')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question34',
            field=models.IntegerField(blank=True, choices=[(0, '매우 강한 부정'), (1, '강한 부정'), (2, '약한 부정'), (3, '매우 약한 부정'), (4, '매우 약한 긍정'), (5, '약한 긍정'), (6, '강한 긍정'), (7, '매우 강한 긍정')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question35',
            field=models.IntegerField(blank=True, choices=[(0, '매우 강한 부정'), (1, '강한 부정'), (2, '약한 부정'), (3, '매우 약한 부정'), (4, '매우 약한 긍정'), (5, '약한 긍정'), (6, '강한 긍정'), (7, '매우 강한 긍정')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question36',
            field=models.IntegerField(blank=True, choices=[(0, '매우 강한 부정'), (1, '강한 부정'), (2, '약한 부정'), (3, '매우 약한 부정'), (4, '매우 약한 긍정'), (5, '약한 긍정'), (6, '강한 긍정'), (7, '매우 강한 긍정')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question37',
            field=models.IntegerField(blank=True, choices=[(0, '매우 강한 부정'), (1, '강한 부정'), (2, '약한 부정'), (3, '매우 약한 부정'), (4, '매우 약한 긍정'), (5, '약한 긍정'), (6, '강한 긍정'), (7, '매우 강한 긍정')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question38',
            field=models.IntegerField(blank=True, choices=[(0, '매우 강한 부정'), (1, '강한 부정'), (2, '약한 부정'), (3, '매우 약한 부정'), (4, '매우 약한 긍정'), (5, '약한 긍정'), (6, '강한 긍정'), (7, '매우 강한 긍정')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Question39',
            field=models.IntegerField(blank=True, choices=[(0, '매우 강한 부정'), (1, '강한 부정'), (2, '약한 부정'), (3, '매우 약한 부정'), (4, '매우 약한 긍정'), (5, '약한 긍정'), (6, '강한 긍정'), (7, '매우 강한 긍정')], null=True),
        ),
    ]
