# Generated by Django 3.1.7 on 2021-03-18 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20210318_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='D_result',
            new_name='voted',
        ),
    ]
